### ISSUE TITLE
Style login.ejs and signup.ejs

### ISSUE THREAD

**Issue by celiackelly** [BigSuggs72/libraryauth#10]
Style login.ejs and signup.ejs to match the index.ejs styles, and maybe make the form inputs look nicer. 

These two pages will have very similar styles, so we may be able to clean up the CSS a bit to use the same classes on both pages (ex: one class instead of having both .login and .signup).

**Comment by bumpylumps** [comment]
I added some styling to the Login and Signup forms, PR for that incoming as well. Was able to get the submit buttons to match the header buttons, and tightened up the form styles a little bit - more info in PR

**Comment by celiackelly** [comment]
I'm working on some additional styling for these forms. I noticed that the <input> tag selector was targeting the submit buttons as well, so I'm working on changing the selectors a bit.
