### ISSUE TITLE
Add favicon and change page titles

### ISSUE THREAD

**Issue by celiackelly** [BigSuggs72/libraryauth#12]
Add books-stack-of-three-svgrepo-com.svg (in the images folder) as a favicon on all ejs pages.
Edit the page titles (for example, maybe "Home" instead of "INDEX"? maybe not all caps?)

<img width="514" alt="Screen Shot 2022-09-04 at 10 56 56 AM" src="https://user-images.githubusercontent.com/81911167/188319931-849ad388-c37f-4aee-9fbe-7a902da9bd6c.png">

**Comment by bumpylumps** [comment]
I got this one! I've updated the page titles and added a favicon to each page. PR incoming!
