### ISSUE TITLE
Add first name (and last name?) to user sign-up

### ISSUE THREAD

**Issue by celiackelly** [BigSuggs72/libraryauth#13]
Goal: to display a user's first name on the books.ejs page, instead of their email. For example: 
"Hi Celia! You have 1 book available." instead of "celiackelly@gmail.com has 1 book available."

<img width="483" alt="Screen Shot 2022-09-04 at 11 02 18 AM" src="https://user-images.githubusercontent.com/81911167/188320104-705272cc-129e-4c23-9da2-d9e855f4d594.png">

I think these are all the steps needed to make this happen:
- [ ] Add first name (and last name?) to the models/User.js 
- [ ] Add form input to the views/signup.ejs page for first name
- [ ] In controllers/auth.js, adjust the postSignup method to require the first name and pass it to the backend when creating a new user
- [ ] Modify views/books.ejs to display the user's first name instead of email (ex: "Hi Celia! You have 1 book available." )

**Comment by missbabelfish** [comment]
I'll try to get this working!

**Comment by missbabelfish** [comment]
with PR #16 this should be all done and ready to go.
